apiVersion: auth-bridge.dev/v1alpha1
kind: Script
metadata:
  name: query-policy
  namespace: auth-bridge-example
spec:
  source: |
    package proxy
    
    default allowed = false
    allowed = true {
      input.query.name == "abc"
    }
    allowed = true {
      input.headers["x-proxy"] == "abc"
    }
  engine:
    rego:
      query: "data.proxy.allowed"