---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: auth-bridge-example
data:
  nginx.conf: |
    events {
      worker_connections 1024;
    }
    http {
      server {
        listen 80;
        server_name localhost;

        location /auth {
            auth_basic "Restricted Area";
            auth_basic_user_file /etc/nginx/.htpasswd;
            root /usr/share/nginx/html;
            try_files /auth.html =404;
        }

        location /no-auth {
            auth_basic off;
            root /usr/share/nginx/html;
            try_files /no-auth.html =404;
        }
      }
    }
  no-auth.html: |
    Hello from no-auth path
  auth.html: |
    Hello from auth path
  .htpasswd: |
    auth-user:$1$FDNvyIWe$pMX38FS311281uVenqcyi0
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: nginx
  name: nginx
  namespace: auth-bridge-example
spec:
  containers:
    - name: nginx
      image: nginx:alpine
      ports:
        - containerPort: 80
      volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
        - name: nginx-config
          mountPath: /etc/nginx/.htpasswd
          subPath: .htpasswd
        - name: nginx-config
          mountPath: /usr/share/nginx/html/auth.html
          subPath: auth.html
        - name: nginx-config
          mountPath: /usr/share/nginx/html/no-auth.html
          subPath: no-auth.html
  volumes:
    - name: nginx-config
      configMap:
        name: nginx-config
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: auth-bridge-example
spec:
  selector:
    app: nginx