apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: auth-bridge-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: auth-bridge
subjects:
- kind: ServiceAccount
  name: auth-bridge
  namespace: auth-bridge
