apiVersion: auth-bridge.dev/v1alpha1
kind: Proxy
metadata:
  name: basic-auth
  namespace: auth-bridge-example
spec:
  address: "http://nginx.auth-bridge-example"
  #address: "http://127.0.0.1:32080"
  auth:
    method:
      basicAuth: {}
    storage:
      secretRef:
        namespace: auth-bridge-example
        name: basic-auth
  policies:
    - script: namespace-policy